import Head from "next/head";
import MainHeader from "@/components/MainHeader";
import HomePic from "@/components/HomePic";
import Thumbnail from "@/components/Thumbnail";
import Contact from "@/components/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Berger Automatismes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainHeader />
        <HomePic />
        <Thumbnail />
        <Contact />
      </main>
    </>
  );
}
